"""empty message

Revision ID: d6d4f30a076d
Revises: ce1768fc9ad5
Create Date: 2026-02-09 00:45:30.545296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d4f30a076d'
down_revision = 'ce1768fc9ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('warning')

    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('requisition_users'), type_='foreignkey')
        batch_op.create_foreign_key('requisition_users', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('recevier_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recevier_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('requisition_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('requisition_users'), 'users', ['recevier_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('receiver_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warning', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
